baseURL = "https://liuzhizhou.github.io"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = "G-0GZRVRLSQV"
paginate = 5
rssLimit = 10
title = "Blog | Liu Zhizhou"


[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe= false
[markup.highlight]
style = "tango"
[markup.tableOfContents]
  endLevel = 6
  ordered = false
  startLevel = 2

[author]
email = "liuzhizhou95@gmail.com"
name = "Liu Zhizhou"

[params]
numberedSubtitles = true
toc = true

