baseURL = "https://liuzhizhou.github.io"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = "G-0GZRVRLSQV"
hasCJKLanguage = true
languageCode = "en"
paginate = 5
rssLimit = 10
theme = "hugo-texify2"
title = "Blog | Liu Zhizhou"

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe= true
[markup.highlight]
style = "tango"
[markup.tableOfContents]
  endLevel = 6
  ordered = false
  startLevel = 2

[author]
email = "liuzhizhou95@gmail.com"
name = "Liu Zhizhou"

[params]
title = "Liu Zhizhou"
numberedSubtitles = true
toc = true
description = "A student who is trying to understand something."
images = ['images/logo.jpg']
footnote = """
Follow me on <a class=link href=https://github.com/liuzhizhou target=_blank rel=noopener>GitHub</a> and 
<a class=link href=https://xueqiu.com/u/4342886534 target=_blank rel=noopener>Xueqiu(雪球)</a>.
<br>
Contact me via <a class=link href = "mailto: liuzhizhou95@gmail.com">Email</a>.
"""

[params.commentEngine]
code = """
<script src="https://giscus.app/client.js"
        data-repo="weastur/hugo-texify2"
        data-repo-id="R_kgDOJwiYnA"
        data-category="Comments"
        data-category-id="DIC_kwDOJwiYnM4CXVgQ"
        data-mapping="title"
        data-strict="1"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="light"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
"""

[params.buymeacoffee]
code = """
"""

[params.sharingbuttons]
facebook = false
twitter = false
email = false
linkedin = false
reddit = false
whatsapp = false
hackernews = false
telegram = false